Reviews style
YevaCheplyhina/tech-architects pull request #6
Opened 2024-10-20 08:40 UTC by Vitos55

2024-10-20 20:16 UTC, YevaCheplyhina requested changes

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/partials/reviews.html
> +<section class="reviews-section">
додайте в класс id="reviews", щоб при натисканні на кнопки в хедері користувача переносило на вашу секцію

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +
треба прописати 
@media screen and (min-width: 1280px) 
{.reviews-section {padding: 100px 100px;) 
так як у версіі для комп'ютера відступи бокові 100рх

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +  padding: 80px 20px;
padding: 80px 0;

так як в базових стилях прописани бокові падінги по 20рх і твій <div class="container" вже має ці падінги.

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +    padding: 100px 32px;
також padding: 100px 0;

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +@media screen and (min-width: 768px) and (max-width: 1023px) {
значення max-width: 1280px, тому що 3 карточки в нас з'являються на комп'ютерній версіі, а це від 1280рх

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +  margin-right: auto;
щоб не прописувати так, зроби:
margin: 0 auto 24px;

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +}
так як перші стилі в нас для мобілки, а там всього один елемент, немає сенсу робити список флексом, тому треба видалити

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +  }
так як в планшетній версіі в нас 2 картки, тут ми можемо зробити список флексами, тоді воно буде застосовуватись від ширини екрану від 768рх. 

але gap в планшетній розмітці в нас 18рх

.reviews-list {
  justify-content: center;
  display: flex;
  gap: 18px;
}

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +  color: #141414;
margin-bottom: 20px;

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +    line-height: 100%;
margin-bottom: 25px;
 
 так як для планшету і комп'ютеру (тобто при min-width:768px) відступ між заголовком і описом 25рх,

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +    max-width: 553px;
margin-bottom: 50px;

так як між текстом і картками в планшетній і комп'ютерній версіях відступ 50рх

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +  padding-top: 25px;
ми не робимо відступи між сусідніми елементами падінгами, бо тоді виходить, що рамка <p> буде притискатися до рамки <h2>

вище прописала де треба зробити margin-bottom, цей падінг треба видалити

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +
відступ між картками в комп'ютерній версії 25рх

@media screen and (min-width: 1280px;) {reviews-list {gap: 25px;}

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +    width: 343px;
треба прописати padding для карток в планшетній і комп'ютерній версії як на макеті

  .reviews-item {
    padding: 20px;
  }

2024-10-20 20:16 UTC, YevaCheplyhina commented on src/css/reviews.css
> +  line-height: 125%;
2 рази прописали line-height, залишаємо той, що 129%

2024-10-20 21:55 UTC, Vitos55 commented on src/css/reviews.css
> +  margin-right: auto;
верх 0/ лево право auto/низ 24?

2024-10-20 21:55 UTC, Vitos55 commented on src/partials/reviews.html
> +<section class="reviews-section">
![Снимок экрана 2024-10-21 005001](https://github.com/user-attachments/assets/cd67d877-b80e-4f5e-a0f3-9b4ecd991712)

2024-10-21 07:08 UTC, YevaCheplyhina requested changes

2024-10-21 07:08 UTC, YevaCheplyhina commented on src/css/reviews.css
> +
вибачте, не так вказала вам padding

media screen and (min-width: 1280px)
{.reviews-section {padding: 100px 0;)

бокові падінги будуть 0, бо в базових стилях я для всіх секцій прописувала їх

2024-10-21 07:08 UTC, YevaCheplyhina commented on src/css/reviews.css
> +}
дивіться:
є два способи прописати марджин
1. через 4 властивості
margin-top - верхній
margin-right - правий
margin-bottom - нижній
margin-left - лівий

2. через властивість margin, якій задається одразу 4 значення в дужках, тобто
margin: 1px 2px 3px 4px:
тоді верхній 1рх
правий 2рх
нижній 3рх
лівий 4рх

3. або задати 2 значення 
margin: 1px 2px;
де вехній і нижній марджин 1рх
лівий і правий 2 рх

4. margin: 0 auto 24px - ваш випадок
верхній марджин 0
лівий і правий авто
нижній 24рх

тобто в цьому випадку ви задали всі марджини

тоді внизу margin-left і margin-right непотрібні, бо ви їх вже вказали в margin

2024-10-22 09:45 UTC, YevaCheplyhina approved these changes

2024-10-22 09:47 UTC, merged